# Generated by Django 3.2.4 on 2021-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('room_type', models.CharField(choices=[('br', 'Bedroom'), ('lr', 'Living Room'), ('sr', 'Store Room')], default='br', max_length=2)),
            ],
        ),
    ]
