# Generated by Django 3.2.4 on 2021-06-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210605_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('bedroom', 'Bedroom'), ('living-room', 'Living Room'), ('store-room', 'Store Room')], default='bedroom', max_length=20),
        ),
    ]
