# Generated by Django 3.2.4 on 2021-06-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_room_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.house'),
        ),
    ]
