# Generated by Django 3.2.4 on 2021-06-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_room_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('bed-room', 'Bedroom'), ('living-room', 'Living Room'), ('store-room', 'Store Room'), ('bath-room', 'Bath Room')], default='bed-room', max_length=20),
        ),
    ]
